// 2_JS_Avancado_Desenvolvimento/Aula_19/Aula_19_Exemplo1.jsx
// Botao.js
import React from 'react';

function Botao({ texto, onClick }) {
  return <button onClick={onClick}>{texto}</button>;
}

export default Botao;

// Contador.js
import React, { useState } from 'react';
import Botao from './Botao';

function Contador() {
  const [contagem, setContagem] = useState(0);

  return (
    <div>
      <p>Contagem: {contagem}</p>
      <Botao texto="Aumentar" onClick={() => setContagem(contagem + 1)} />
      <Botao texto="Diminuir" onClick={() => setContagem(contagem - 1)} />
    </div>
  );
}

export default Contador;

// 2_JS_Avancado_Desenvolvimento/Aula_19/Aula_19_Exemplo1.vue
<!-- Botao.vue -->
<template>
    <button @click="onClick">{{ texto }}</button>
  </template>
  
  <script>
  export default {
    props: ['texto', 'onClick']
  };
  </script>
  
  <!-- Contador.vue -->
  <template>
    <div>
      <p>Contagem: {{ contagem }}</p>
      <Botao texto="Aumentar" :onClick="aumentar" />
      <Botao texto="Diminuir" :onClick="diminuir" />
    </div>
  </template>
  
  <script>
  import Botao from './Botao.vue';
  
  export default {
    components: { Botao },
    data() {
      return {
        contagem: 0
      };
    },
    methods: {
      aumentar() {
        this.contagem++;
      },
      diminuir() {
        this.contagem--;
      }
    }
  };
  </script>
