// 2_JS_Avancado_Desenvolvimento/Aula_19/Aula_19_Exemplo2.vue
<!-- Formulario.vue -->
<template>
    <div>
      <input v-model="nome" placeholder="Digite seu nome" />
      <button @click="aoEnviarNome">Enviar</button>
    </div>
  </template>
  
  <script>
  export default {
    data() {
      return {
        nome: ''
      };
    },
    methods: {
      aoEnviarNome() {
        this.$emit('enviar-nome', this.nome);
      }
    }
  };
  </script>
  
  <!-- Perfil.vue -->
  <template>
    <p>Bem-vindo, {{ nome }}!</p>
  </template>
  
  <script>
  export default {
    props: ['nome']
  };
  </script>
  
  <!-- App.vue -->
  <template>
    <div>
      <Formulario @enviar-nome="definirNome" />
      <Perfil v-if="nome" :nome="nome" />
    </div>
  </template>
  
  <script>
  import Formulario from './Formulario.vue';
  import Perfil from './Perfil.vue';
  
  export default {
    components: { Formulario, Perfil },
    data() {
      return {
        nome: ''
      };
    },
    methods: {
      definirNome(nome) {
        this.nome = nome;
      }
    }
  };
  </script>

// 2_JS_Avancado_Desenvolvimento/Aula_19/Aula_19_Exemplo2.jsx
// Formulario.js
import React, { useState } from 'react';

function Formulario({ aoEnviar }) {
  const [nome, setNome] = useState('');

  return (
    <div>
      <input
        type="text"
        value={nome}
        onChange={(e) => setNome(e.target.value)}
        placeholder="Digite seu nome"
      />
      <button onClick={() => aoEnviar(nome)}>Enviar</button>
    </div>
  );
}

export default Formulario;

// Perfil.js
import React from 'react';

function Perfil({ nome }) {
  return <p>Bem-vindo, {nome}!</p>;
}

export default Perfil;

// App.js
import React, { useState } from 'react';
import Formulario from './Formulario';
import Perfil from './Perfil';

function App() {
  const [nome, setNome] = useState('');

  return (
    <div>
      <Formulario aoEnviar={setNome} />
      {nome && <Perfil nome={nome} />}
    </div>
  );
}

export default App;
